### PR TITLE
refactor: add prettier, editorconfig and git hooks

### PR DESCRIPTION
**Pull request by dangreen**
https://github.com/swc-project/cli/issues/91

- Formatted code will be in another PR
- When you will approve this PR, I will make the same PRs to other swc reops

### CODE REVIEW

**Comment by kdy1** [comment]
Can you rebase this?

**Comment by dangreen** [comment]
@kdy1 1sec

**Comment by dangreen** [comment]
@kdy1 done

**Review by kdy1 — APPROVED** [review]
Thank you!

**Pull request merged**
