### PR TITLE
feat: add --out-file-extension (with tests)

### PR DESCRIPTION
**Pull request by Codex-**
Trying to get some traction on #131 

- Reapply the minimal base changes
- Add tests

This changeset is smaller as it does not reformat the tests to the new/current style, this makes the diff quite large and should probably be done in isolation so as to not muddy the intent of the original PR.

- https://github.com/swc-project/swc/pull/4343
- https://github.com/swc-project/swc/issues/3067

### CODE REVIEW

**Comment by Codex-** [comment]
The failures are not as a result of this pr:
`node 12`:
```
yarn install v1.22.19
[1/[5](https://github.com/swc-project/cli/actions/runs/4420735544/jobs/7750788364#step:4:6)] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error strtok3@7.0.0: The engine "node" is incompatible with this module. Expected version ">=14.1[6](https://github.com/swc-project/cli/actions/runs/4420735544/jobs/7750788364#step:4:7)". Got "12.22.12"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

The other failure is on `npm audit` (no package changes here), this is covered by the addition of the Socket Security integration?

**Comment by kwonoj** [comment]
I'm curious if this needs to be

- allowlist known supported extensions (js, mjs, .cjs,...)
- dependent to the config: i.e if extension is .mjs and trapspilied output is cjs, should it be considered as valid combination?

**Comment by Codex-** [comment]
> I'm curious if this needs to be
> 
>     * allowlist known supported extensions (js, mjs, .cjs,...)
> 
>     * dependent to the config: i.e if extension is .mjs and trapspilied output is cjs, should it be considered as valid combination?

Yeah so these are definitely reasonable questions to ask. Should these be concerns of this CLI package or of swc/core? Or should the onus be on the consumer to ensure the flags are being used in a valid way? 

If you'd prefer, I can add in a check for combinations that are valid. Or, at least in the case where they're not typically valid (maybe a consumer has an odd case where they want a typically invalid combination for some edge case? Or want to use a bespoke extension for some other process to filter on with a glob pattern? etc) 

Thoughts?

**Comment by kwonoj** [comment]
I _think_ those validation should be needed, however peeking bit more I'm inclined to say it should occur lower level inside of swc_core, or at least in swcx (native binary side) instead of this 1.x js implementation attempts to resolve it.

**Comment by luozhihua** [comment]
any update?

**Review by rxmarbles — APPROVED** [review]

**Comment by gossi** [comment]
I was in the situation to write a package that ships as cjs and esm. My idea was to have files as `dist/file.js` and `dist/file.cjs`. So I patched my local `@swc/cli` with the two files from this PR.

My `package.json`:

```json
{
  "exports": {
    "./*": {
      "require": "dist/*.cjs",
      "default": "dist/*.js",
    }
  }
}
```

I found it failing in two situations, that `swc` _might_ take care of. It is about relative imports, let's say this code:

```ts
import Something from './another-file';

function doSomehwat(something: Something) {}
```

## 1) Project uses `moduleResolution` with `node16` or `nodenext`

With that setting even in a TS file, you must add the extension to your import. The first line from above, should be this then:

```ts
import Something from './another-file.js';
```

Which will get transpiled 1:1 - however, when this file has a `.cjs` extension the import targets the wrong file. In that case, the extension in the file must be converted, too. To this:

```js
import Something from './another-file.cjs';
```

In order to keep the promise of transpiling

## 2) Project uses `moduleResolution` with `bundler`

In order to avoid having the extensions, the TS team added `bundler` as option, when transpiling is accompanied with bundling. That is the import doesn't need to contain the `.js` file extension in the source file (first code example, above).

Sounds good to use it then, no?

For my example, it didn't work. I had `.js` and `.cjs` files as siblings in my `dist/` folder, yet it didn't work. Why?

Here node js CJS loader respects the `exports` only when this is a fully qualified import, beginning with the name of the package, related line of code: https://github.com/nodejs/node/blob/ccf46ba0f5ce02ae85b8bdb5e29acfc376caf9fc/lib/internal/modules/cjs/loader.js#L536

As a result, in the final environment, the `.cjs` file loaded a `.js` (esm) file and it was breaking.

## Workaround

My dist folder now looks like this:

```
dist/
- cjs/
- declarations/
- esm/
```

So, the resolvers can do their job.

## Potential Solution

`swc` might to decide to rename the generated imports based on the file extension to circumvent the problem and keep the stability guarantee. I dunno how babel is doing that, probably there is bundleing on top, that takes care of that.

## Conclusion

This PR introduces an extension to the API - a very good one imho. It doesn't really matter for that API if it is implemented in js or rust at first, this can be moved behind the scenes. The planned validations are also good to enhance the DX as it warns (or errors) about potential invalid usage. But they wouldn't have prevented me from running into the issues I outlined here.

If they are ok for you to have and keep that as a way to collect feedback around this, then I'd say ship it 👍

**Comment by Codex-** [comment]
Added by #286

**Pull request closed without merging**
