### PR TITLE
Integration ci

### PR DESCRIPTION
**Pull request by chyzwar**
- added GitHub actions for test, build
- added GitHub action for integration tests for spack and swc cli
- removed scripts as they were used for integration testing?

I took a slightly different approach with these integration tests. Instead of installing as global, I would install and use link. I am not sure if this is better. 

I also cleaned .gitignore. My personal preference is to not have auto generated .gitignore as they tend to be noisy. if you do not like it I can revert.

Is fixtures for amd.js is used for anything?

### CODE REVIEW

**Comment by chyzwar** [comment]
@kdy1  can you please publish @swc/cli otherwise this branch windows integration tests will keep failing. It is like chicken and egg problem. As a part of changes in this branch I changed to use swc to compile instead of tsc.

**Comment by kdy1** [comment]
Ah, sorry. I forgot publishing it.
Publsihed a new version.

**Comment by chyzwar** [comment]
https://github.com/chyzwar/cli/runs/2691458442?check_suite_focus=true

Integration tests are now passing. These tests would run in matrix:
node version 12.x, 14.x, 16.x
os: macos-latest, windows-latest, ubuntu-latest

Integration test have small bash funbction that verify number of files in source vs output.

Test would test spack and swc compilation on three.js and rxjs. I wanted tio use angular project but there were too many errors.

This branch also:
- switch transpilation to swc

**Comment by chyzwar** [comment]
I think it is now ready for review.

**Review by kdy1 — APPROVED** [review]
Thanks a lot!!

**Comment by kdy1** [comment]
I published a new version, and tests are quite satsifying. Thank you again!

**Pull request merged**
