### PR TITLE
feat: add --out-file-extension 

### PR DESCRIPTION
**Pull request by RiESAEX**
relative to 
https://github.com/swc-project/swc/pull/4343
https://github.com/swc-project/swc/issues/3067

### CODE REVIEW

**Comment by tryggvigy** [comment]
Is anything blocking this PR? Would love to get this feature in

**Review by kwonoj — COMMENTED** [review]
Are CI failures expected?

+ we need to pick this changes to swc's native cli as well.

**Comment by RiESAEX** [comment]
> Are CI failures expected

I'm not sure, but it doesn't seem relevant to this pr.

**Comment by bahtou** [comment]
any updates on this? ran into an issue at work and would rather have this update than switch projects.

**Comment by shellscape** [comment]
When there's only 12 pull requests open and this hasn't gotten any love for over a year from maintainers, it's a bad look.

**Comment by kdy1** [comment]
Can you rebase?

**Comment by RiESAEX** [comment]
I think #286 already implemented this.

**Pull request closed without merging**
